import { exec as execCallback, spawn, ChildProcess } from 'child_process';
import { promisify } from 'util';
import { resolve } from 'path';
import { existsSync, promises as fs } from 'fs';
import { logger } from './logger.js';
import { config } from '../config/index.js';
import {
  sendHeartbeat,
  HeartbeatAuthError,
  type HeartbeatResult,
} from './basis-cloud.js';

const execAsync = promisify(execCallback);

/**
 * Wraps the `frpc` CLI for Basis Remote — the paid lastname.home-basis.com
 * tunnel service. frpc dials OUT to our relay (frps); the relay's control
 * plane authenticates the box via the tunnel token sent in frpc metadata.
 *
 * Supervision strategy is copied from cloudflared.ts (spawn as a child of the
 * backend, self-healing respawn with capped exponential backoff) rather than
 * extracted into a shared util: the cloudflared path is load-bearing on real
 * installs and has no unit tests to guard a refactor, and the lifecycles
 * genuinely differ — frpc needs a config file on disk and owns a heartbeat
 * loop coupled to the child's lifetime.
 * TODO: extract a shared ChildSupervisor once both tunnels are stable.
 */

const LOCAL_FRPC = resolve(process.cwd(), 'bin', 'frpc');

function frpcBinary(): string {
  return existsSync(LOCAL_FRPC) ? LOCAL_FRPC : 'frpc';
}

export type BasisRemoteIssue =
  | 'not_installed'
  | 'spawn_failed'
  | 'child_exited'
  | 'unknown_error';

/** Mirrors HouseholdSettings.remoteAccess.basisRemote. */
export interface BasisRemoteConfig {
  tenantId: string;
  subdomain: string;
  hostname: string;
  tunnelToken: string;
  relay: { serverAddr: string; serverPort: number };
}

export interface BasisRemoteHeartbeatState {
  /** Last successful heartbeat payload, if any. */
  status?: 'active' | 'suspended' | 'canceled';
  tier?: string;
  usage?: { monthGB: number; capGB: number };
  fetchedAt?: string;
  /** True when the last successful fetch is older than two intervals. */
  stale: boolean;
  /** 401/403 — the cloud no longer recognizes this box's token. */
  authFailed?: boolean;
}

export interface BasisRemoteStatus {
  installed: boolean;
  version?: string;
  running: boolean;
  /** Set if the most recent spawn failed or the child exited unexpectedly. */
  lastError?: string;
  issues: BasisRemoteIssue[];
  hostname?: string;
  subdomain?: string;
  heartbeat?: BasisRemoteHeartbeatState;
}

const EXEC_TIMEOUT_MS = 5_000;

let _exec: typeof execAsync = execAsync;
let _spawn: typeof spawn = spawn;
let _runDir = resolve(process.cwd(), 'run');
let _heartbeatIntervalMs = 15 * 60_000;
let _graceMs = 750;
let _backoffBaseMs = 1_000;

export function __setExecForTests(fn: typeof execAsync | null): void {
  _exec = fn ?? execAsync;
}

export function __setSpawnForTests(fn: typeof spawn | null): void {
  _spawn = fn ?? spawn;
}

export function __setRunDirForTests(dir: string | null): void {
  _runDir = dir ?? resolve(process.cwd(), 'run');
}

export function __setHeartbeatIntervalForTests(ms: number | null): void {
  _heartbeatIntervalMs = ms ?? 15 * 60_000;
}

export function __setTimingsForTests(t: { graceMs?: number; backoffBaseMs?: number } | null): void {
  _graceMs = t?.graceMs ?? 750;
  _backoffBaseMs = t?.backoffBaseMs ?? 1_000;
}

function frpcConfigPath(): string {
  return resolve(_runDir, 'frpc.toml');
}

// ─── config file ───────────────────────────────────────────────────────────

// Values are interpolated into a TOML template, so constrain the charset hard:
// a hostile or buggy cloud response must not be able to inject TOML keys.
const SAFE_TOKEN = /^[A-Za-z0-9_-]+$/;
const SAFE_HOSTNAME = /^[A-Za-z0-9](?:[A-Za-z0-9.-]*[A-Za-z0-9])?$/;

export function validateBasisRemoteConfig(cfg: BasisRemoteConfig): string | null {
  if (!SAFE_TOKEN.test(cfg.tenantId)) return 'tenantId contains unexpected characters';
  if (!SAFE_TOKEN.test(cfg.subdomain)) return 'subdomain contains unexpected characters';
  if (!SAFE_TOKEN.test(cfg.tunnelToken)) return 'tunnelToken contains unexpected characters';
  if (!SAFE_HOSTNAME.test(cfg.relay.serverAddr)) return 'relay serverAddr is not a valid hostname';
  if (
    !Number.isInteger(cfg.relay.serverPort) ||
    cfg.relay.serverPort < 1 ||
    cfg.relay.serverPort > 65535
  ) {
    return 'relay serverPort is out of range';
  }
  return null;
}

/** Render the frpc TOML. Exported for tests. */
export function buildFrpcToml(cfg: BasisRemoteConfig, localPort: number): string {
  return `# Generated by Basis — do not edit; regenerated on every tunnel start.
serverAddr = "${cfg.relay.serverAddr}"
serverPort = ${cfg.relay.serverPort}
user = "${cfg.tenantId}"
metadatas.token = "${cfg.tunnelToken}"
log.to = "console"
log.level = "info"

# Application-layer heartbeats are off by default under TCP mux, but the
# relay's control plane authorizes each Ping — this is how suspension takes
# effect promptly instead of only at the next reconnect.
transport.heartbeatInterval = 30

[[proxies]]
name = "web"
type = "http"
subdomain = "${cfg.subdomain}"
localPort = ${localPort}
`;
}

async function writeFrpcConfig(cfg: BasisRemoteConfig): Promise<string> {
  const invalid = validateBasisRemoteConfig(cfg);
  if (invalid) throw new Error(`Refusing to write frpc config: ${invalid}`);
  await fs.mkdir(_runDir, { recursive: true });
  const path = frpcConfigPath();
  // Contains the tunnel token — owner-only.
  await fs.writeFile(path, buildFrpcToml(cfg, config.PORT), { mode: 0o600 });
  return path;
}

// ─── child-process supervision (see cloudflared.ts for the rationale) ──────

let child: ChildProcess | null = null;
let lastError: string | undefined;

let activeConfig: BasisRemoteConfig | null = null; // null ⇒ intentionally stopped
// Survives stopChildOnly() so the status can keep naming the linked hostname
// after a cancel/unlink stops the tunnel. Cleared only by stopBasisRemote().
let lastKnownIdentity: { hostname: string; subdomain: string } | null = null;
let restartTimer: NodeJS.Timeout | null = null;
let stableTimer: NodeJS.Timeout | null = null;
let restartAttempts = 0;
const MAX_BACKOFF_MS = 60_000;
const STABLE_AFTER_MS = 60_000;

// Ring buffer of recent frpc output so "login to server failed: token mismatch"
// style messages reach the UI when the child exits.
const OUTPUT_BUFFER_LINES = 10;
let recentOutput: string[] = [];

function rememberOutput(chunk: string): void {
  for (const line of chunk.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    recentOutput.push(trimmed);
    if (recentOutput.length > OUTPUT_BUFFER_LINES) recentOutput.shift();
  }
}

function isAlive(): boolean {
  return !!child && child.exitCode === null && !child.killed;
}

function clearTimers(): void {
  if (restartTimer) {
    clearTimeout(restartTimer);
    restartTimer = null;
  }
  if (stableTimer) {
    clearTimeout(stableTimer);
    stableTimer = null;
  }
}

function scheduleRestart(): void {
  if (!activeConfig) return;
  if (restartTimer || isAlive()) return;
  const delay = Math.min(MAX_BACKOFF_MS, _backoffBaseMs * 2 ** restartAttempts);
  restartAttempts += 1;
  logger.warn({ delay, attempt: restartAttempts }, 'Scheduling frpc restart');
  restartTimer = setTimeout(() => {
    restartTimer = null;
    const cfg = activeConfig;
    if (!cfg || isAlive()) return;
    void startBasisRemote(cfg);
  }, delay);
}

// ─── heartbeat loop ─────────────────────────────────────────────────────────

interface HeartbeatInternal {
  result?: HeartbeatResult;
  fetchedAt?: number;
  authFailed: boolean;
}

let heartbeatTimer: NodeJS.Timeout | null = null;
let lastHeartbeat: HeartbeatInternal = { authFailed: false };

function stopHeartbeat(): void {
  if (heartbeatTimer) {
    clearInterval(heartbeatTimer);
    heartbeatTimer = null;
  }
}

async function runHeartbeat(): Promise<void> {
  const cfg = activeConfig;
  if (!cfg) return;
  try {
    const result = await sendHeartbeat(cfg.tunnelToken);
    lastHeartbeat = { result, fetchedAt: Date.now(), authFailed: false };
    if (result.status === 'canceled') {
      // Subscription is gone. Stop the child + heartbeat, but keep the
      // persisted settings and the last heartbeat so the UI can explain.
      // Runtime-only: a backend restart retries once and re-cancels.
      logger.warn('Basis Remote subscription canceled — stopping tunnel');
      stopChildOnly();
      stopHeartbeat();
    }
    // 'suspended' intentionally keeps frpc running: the relay is the
    // enforcement point (it drops/rejects us) and the supervisor's capped
    // backoff means reconnect attempts stay cheap.
  } catch (err) {
    if (err instanceof HeartbeatAuthError) {
      logger.warn('Basis Remote token no longer recognized — stopping tunnel');
      lastHeartbeat = { ...lastHeartbeat, authFailed: true };
      stopChildOnly();
      stopHeartbeat();
      return;
    }
    // Network-shaped: keep last-known state; staleness is derived on read.
    logger.debug({ err }, 'Basis Remote heartbeat failed (transient)');
  }
}

function startHeartbeat(): void {
  stopHeartbeat();
  void runHeartbeat();
  heartbeatTimer = setInterval(() => void runHeartbeat(), _heartbeatIntervalMs);
  // Don't hold the process open for the heartbeat alone.
  heartbeatTimer.unref?.();
}

function heartbeatState(): BasisRemoteHeartbeatState | undefined {
  const { result, fetchedAt, authFailed } = lastHeartbeat;
  if (!result && !authFailed) return undefined;
  return {
    status: result?.status,
    tier: result?.tier,
    usage: result?.usage,
    fetchedAt: fetchedAt ? new Date(fetchedAt).toISOString() : undefined,
    stale: fetchedAt ? Date.now() - fetchedAt > 2 * _heartbeatIntervalMs : true,
    authFailed: authFailed || undefined,
  };
}

// ─── public API ─────────────────────────────────────────────────────────────

async function detectInstalled(): Promise<{ installed: boolean; version?: string }> {
  try {
    // frpc prints a bare version string, e.g. "0.61.1".
    const { stdout } = await _exec(`${frpcBinary()} -v`, { timeout: EXEC_TIMEOUT_MS });
    const version = stdout.trim().split('\n')[0]?.trim() || undefined;
    return { installed: true, version };
  } catch (err) {
    logger.debug({ err }, 'frpc -v failed');
    return { installed: false };
  }
}

export async function getBasisRemoteStatus(): Promise<BasisRemoteStatus> {
  const { installed, version } = await detectInstalled();
  const base = {
    hostname: activeConfig?.hostname ?? lastKnownIdentity?.hostname,
    subdomain: activeConfig?.subdomain ?? lastKnownIdentity?.subdomain,
    heartbeat: heartbeatState(),
  };
  if (!installed) {
    return { installed: false, running: false, issues: ['not_installed'], ...base };
  }
  const running = isAlive();
  return {
    installed: true,
    version,
    running,
    lastError,
    issues: lastError && !running ? ['child_exited'] : [],
    ...base,
  };
}

/**
 * Write the frpc config and spawn `frpc -c <config>` as a backend-managed
 * child. Idempotent: if already running, returns the existing status.
 */
export async function startBasisRemote(cfg: BasisRemoteConfig): Promise<BasisRemoteStatus> {
  if (isAlive()) {
    return getBasisRemoteStatus();
  }
  const { installed } = await detectInstalled();
  if (!installed) {
    return { installed: false, running: false, issues: ['not_installed'] };
  }

  let configPath: string;
  try {
    configPath = await writeFrpcConfig(cfg);
  } catch (err) {
    const message = (err as Error).message;
    lastError = message;
    logger.warn({ err }, 'Failed to write frpc config');
    return { installed: true, running: false, lastError: message, issues: ['spawn_failed'] };
  }

  // Remember the config so the exit handler can respawn unattended and the
  // heartbeat loop knows which token to report with.
  activeConfig = cfg;
  lastKnownIdentity = { hostname: cfg.hostname, subdomain: cfg.subdomain };

  return new Promise((resolvePromise) => {
    try {
      const proc = _spawn(frpcBinary(), ['-c', configPath], {
        stdio: ['ignore', 'pipe', 'pipe'],
        detached: false,
      });

      let resolved = false;
      const finish = (status: BasisRemoteStatus) => {
        if (resolved) return;
        resolved = true;
        resolvePromise(status);
      };

      recentOutput = [];
      proc.stdout?.on('data', (d) => {
        const text = d.toString();
        rememberOutput(text);
        logger.debug({ src: 'frpc' }, text.trim());
      });
      proc.stderr?.on('data', (d) => {
        const text = d.toString();
        rememberOutput(text);
        logger.debug({ src: 'frpc' }, text.trim());
      });

      proc.on('error', (err) => {
        lastError = err.message;
        child = null;
        if (stableTimer) {
          clearTimeout(stableTimer);
          stableTimer = null;
        }
        logger.warn({ err }, 'frpc spawn error');
        scheduleRestart();
        finish({
          installed: true,
          running: false,
          lastError: err.message,
          issues: ['spawn_failed'],
          hostname: cfg.hostname,
          subdomain: cfg.subdomain,
          heartbeat: heartbeatState(),
        });
      });

      proc.on('exit', (code, signal) => {
        // Only react if this was unexpected — stopChildOnly() clears `child`
        // before killing, so this handler won't see it and won't respawn.
        if (child === proc) {
          const detail = recentOutput.length ? ` — ${recentOutput.join(' | ')}` : '';
          lastError = `exited with code=${code} signal=${signal}${detail}`;
          child = null;
          if (stableTimer) {
            clearTimeout(stableTimer);
            stableTimer = null;
          }
          logger.warn({ code, signal, recentOutput }, 'frpc exited unexpectedly');
          scheduleRestart();
        }
      });

      child = proc;
      lastError = undefined;
      if (stableTimer) clearTimeout(stableTimer);
      stableTimer = setTimeout(() => {
        stableTimer = null;
        restartAttempts = 0;
      }, STABLE_AFTER_MS);

      startHeartbeat();

      // Give frpc a moment to bail on a clearly-broken config/rejected login
      // before returning success (same 750ms grace as cloudflared).
      setTimeout(() => {
        finish({
          installed: true,
          running: isAlive(),
          lastError,
          issues: isAlive() ? [] : ['child_exited'],
          hostname: cfg.hostname,
          subdomain: cfg.subdomain,
          heartbeat: heartbeatState(),
        });
      }, _graceMs);
    } catch (err) {
      logger.warn({ err }, 'frpc spawn threw synchronously');
      resolvePromise({
        installed: true,
        running: false,
        lastError: (err as Error).message,
        issues: ['spawn_failed'],
      });
    }
  });
}

/** Kill the child without clearing activeConfig/heartbeat state — used when
 *  the cloud says canceled/unlinked and we want the status to keep explaining
 *  why the tunnel is down. */
function stopChildOnly(): void {
  clearTimers();
  restartAttempts = 0;
  if (!child) return;
  const proc = child;
  child = null;
  // Prevent the exit handler's respawn path (it checks child === proc), and
  // prevent scheduleRestart from ever firing again for this config.
  activeConfig = null;
  try {
    proc.kill('SIGTERM');
    setTimeout(() => {
      if (proc.exitCode === null && !proc.killed) {
        proc.kill('SIGKILL');
      }
    }, 5_000).unref?.();
  } catch (err) {
    logger.warn({ err }, 'frpc kill failed');
  }
}

export function stopBasisRemote(): { stopped: boolean } {
  // Cancel supervision + heartbeat first so nothing respawns what we're
  // about to intentionally kill.
  activeConfig = null;
  lastKnownIdentity = null;
  restartAttempts = 0;
  clearTimers();
  stopHeartbeat();
  lastHeartbeat = { authFailed: false };

  // Best-effort removal of the on-disk config (contains the token).
  void fs.rm(frpcConfigPath(), { force: true }).catch(() => undefined);

  if (!child) return { stopped: false };
  const proc = child;
  child = null;
  lastError = undefined;
  try {
    proc.kill('SIGTERM');
    setTimeout(() => {
      if (proc.exitCode === null && !proc.killed) {
        proc.kill('SIGKILL');
      }
    }, 5_000).unref?.();
    return { stopped: true };
  } catch (err) {
    logger.warn({ err }, 'frpc kill failed');
    return { stopped: false };
  }
}

/** Restart the tunnel if a config was previously stored. Used on backend startup. */
export async function resumeBasisRemote(
  cfg: BasisRemoteConfig | null | undefined
): Promise<void> {
  if (!cfg?.tunnelToken) return;
  if (isAlive()) return;
  logger.info('Resuming Basis Remote tunnel from persisted settings');
  await startBasisRemote(cfg);
}
